### ISSUE TITLE
window itself is both a getter and a base

### ISSUE THREAD

**Issue by jackbsteinberg** [jackbsteinberg/get-originals-rewriter#49]
When doing window get/sets, the current pattern sets them up like so:

```js
window.status = 'open';
const n = window.name;
// transforms to
Reflect_apply(Window_status_set, window, ['open']);
const n = Reflect_apply(Window_name_get, window);
```

This will prove to be an issue once #29 is resolved, since `window` on its own is a getter. This means window get/sets will need to be treated like this:

```js
window.status = 'open';
const n = window.name;
// transforms to
Window_status_set('open');
const n = Window_name_get();
```

**Comment by fergald** [comment]
Why wouldn't it be something like

Reflect_apply(Window_name_get, Window_getter())

?

**Comment by domenic** [comment]
I'm not sure what `Window_getter()` would be in that scenario. If you mean that it's the getter for the global `window` property (which we would normally name `Window_window_get`), then, why are you making an exception and calling that particular global-property getter with no this value, while you're choosing to call `Window_name_get` with a this value?

**Comment by fergald** [comment]
If `Window_window_get` is the thing that gives you the window object then what I should I have written was

```js
Reflect_apply(Window_name_get, Window_window_get())
```

I'm trying to reduce the number of special cases and avoid embedding an assumption that there is only one instance of Window in the world.

It seems like window's getters and setters are all going to be special cased with `Window_status_set` etc not taking a this but still operating on an object instance. It would be nicer if the only special case was for _getting_ that the special instance of `Window`. Then the getters and setters are no longer special. That original doesn't have to be named `Window_window_get` (that should probably continue to just exist as something that returns a getter that needs a this). It would be something special since the window we want is _the_ special instance of Window that is injected into the namespace (unlike e.g. `document` which is just a thing you implicitly get from `window`).

Also, it's not the case that window is the only instance of Window in the world. What about

```js
const n = frame.contentWindow.name;
```

This has to become

```js
const n = Window_name_get(frame.contentWindow);
```

(actually there should proabably be a getter in there for `.contentWindow` but you know what I mean).

**Comment by fergald** [comment]
I think there is a concrete problem with the current approach. Try this

```html
<iframe id=i src="frame.html">
<script>
  let wScrollBy = scrollBy;
  let iScrollBy = i.contentWindow.scrollBy;
  console.log(wScrollBy === iScrollBy);

  let wClose = close;
  let iClose = i.contentWindow.close;
  console.log(wClose === iClose);
</script>
```

The output is
```
false
true
```

Some things on Window are auto-bound to the instance and some are unbound methods. So we can't in general handle globals by just translating them to `Window_foo` because some of them need to know their instance object.

I'm not sure how to translate above script using the current approach but it seems like we would need for 2 versions of  Window_scroll_by one that is already bound to the global and one that isn't.

Is there some other way?


The conceptual point I was trying to make (although I'm actually not sure this is really what's happening under the hood) is that we can think of usage of global variables short-hand for accesses on the global object. I.e

```js
scrollBy(0, 100);
```

is really

```js
{the global object}.scrollBy(0, 100);
```

For script running in a window the global object is an instance of Window, for script running in a service worker it's an instance of WorkerGlobalScope(?). So the way to handle these is to provide a getter for the global, maybe `Global_get` (or maybe `Window_get` and `WorkerGlobalScope_get`, I'm just picking one for example) then translate

```js
scrollBy(0, 100);
i.contentWindow.scrollBy(0, 100);
```

to

```js
Reflect_apply(Window_scroll_by, Global_get(), 0, 100);
Reflect_apply(Window_scroll_by, i.contentWindow, 0, 100);
```

**Comment by fergald** [comment]
OK. Thanks for the explanation. Is it worth filing/fixing bugs?

**Comment by domenic** [comment]
> Is it worth filing/fixing bugs?

I ran the test again and it appears to output false in both cases in Canary. So it looks like this was fixed :). http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=7176

I think it is related to https://bugs.chromium.org/p/chromium/issues/detail?id=761755 but I don't see mentions of this specific scenario (function properties) in that bug or any of the ones it blocks.

I'll close this and file a new issue for adding tests that exercise separate windows.
